### ISSUE TITLE
ISSUE: Copy from Previous Prefabs not working as intended

### ISSUE THREAD

**Issue by DeCyi** [haruchanz64/PrefabGenerator#1]
### **Copy from previous Prefabs is not working after generating a prefab.**

Step:
1. Create a prefab with a single component.
2. Generate that said prefab.
3. Click copy components from last prefab.

Result: 
- No previous component to copy from.

Potential issues:
1. Problem with copying multiple components from a prefab.
2. The editor does not recognize the previous prefabs generated.

**Comment by haruchanz64** [comment]
This has been fixed in Version 1.0.2
